### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zzzz438** [sinall/ShiPanE-Python-SDK#13]
在win1064位下面执行
pip install --pre --no-binary shipane_sdk shipane_sdk
的时候，提示
Command "python setup.py egg_info" failed with error code 1 in C:\Temp\pip-build-h7z4i7i6\tushare\

**Comment by sinall** [comment]
重试。或者先安装 tushare 试试。

**Comment by sinall** [comment]
@zzzz438 问题解决了没？
